identifier_name:
 min_length:
    error: 3
 excluded:
    - id
 allowed_symbols: "_"
line_length:
  warning: 140
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
disabled_rules:
   - force_cast
   - force_unwrapping
   - force_try
